"""shareable statements

Revision ID: 425ad53d7a0b
Revises: a54cb280c451
Create Date: 2026-09-04 17:45:42.259913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425ad53d7a0b'
down_revision = 'a54cb280c451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('shared_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('share_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_statements_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statements_share_token'))
        batch_op.drop_column('share_expires_at')
        batch_op.drop_column('shared_at')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
