"""password reset tokens

Revision ID: 70634ee6cd70
Revises: 425ad53d7a0b
Create Date: 2026-09-04 17:51:17.608569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70634ee6cd70'
down_revision = '425ad53d7a0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reset_expires', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.drop_column('reset_expires')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
