"""initial schema

Revision ID: a54cb280c451
Revises: 
Create Date: 2026-09-03 20:40:25.323482

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = 'a54cb280c451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('income_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'MPESA', name='incomemethod'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('sync_status', sa.Enum('SYNCED', 'PENDING', 'FAILED', name='syncstatus'), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'client_uuid', name='uq_income_entry_worker_client')
    )
    with op.batch_alter_table('income_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_entries_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_entries_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_entries_worker_id'), ['worker_id'], unique=False)

    op.create_table('mpesa_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('entries_count', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mpesa_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mpesa_imports_worker_id'), ['worker_id'], unique=False)

    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statements_worker_id'), ['worker_id'], unique=False)

    op.create_table('statement_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('income_entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['income_entry_id'], ['income_entries.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statement_entries')
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statements_worker_id'))

    op.drop_table('statements')
    with op.batch_alter_table('mpesa_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_imports_worker_id'))

    op.drop_table('mpesa_imports')
    with op.batch_alter_table('income_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_entries_worker_id'))
        batch_op.drop_index(batch_op.f('ix_income_entries_date'))
        batch_op.drop_index(batch_op.f('ix_income_entries_client_uuid'))

    op.drop_table('income_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###

    # Postgres keeps ENUM types after the tables using them are dropped, which
    # breaks the next upgrade. Drop them explicitly.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        sa.Enum(name="incomemethod").drop(bind, checkfirst=True)
        sa.Enum(name="syncstatus").drop(bind, checkfirst=True)
